### ISSUE TITLE
商品検索画面で一致しない場合のエラー文がおかしい

### ISSUE THREAD

**Issue by sugitaku03031** [190143/yse2020#2]

**Comment by m25na** [comment]
Warning: A non-numeric value encountered in C:\xampp\htdocs\yse2020\search_result.php on line 52

**Comment by m25na** [comment]
![image](https://user-images.githubusercontent.com/69028011/99465460-d704d100-297d-11eb-9f60-1526bf756246.png)

**Comment by m25na** [comment]
![Uploading image.png…]()

**Comment by m25na** [comment]
![image](https://user-images.githubusercontent.com/69028011/99465504-eedc5500-297d-11eb-909c-7618a4b900cc.png)

**Comment by sugitaku03031** [comment]
コミット: 6bd66bb98bc23dcfb1b453dc468f890a08cda54d [6bd66bb]
親: ba5936bc63
作者: 190143 <190143dl@yse-c.net>
日時: 2020年11月18日 9:26:42
コミット者: 190143
一致する書籍がなかったらエラー文を表示させて戻る

にて修正しました。
